(* ::Package:: *)

Get[FileNameJoin[{NotebookDirectory[], "cfpsen.m"}]]
Get[FileNameJoin[{NotebookDirectory[], "eigen.m"}]]
Get[FileNameJoin[{NotebookDirectory[], "young.m"}]]

(*<</home/gavin/NotreDame/IBM Related/IBM code/ibmcl.m*)

(*** Interacting boson model for (l1+l2+...+lp)^Nb bosons ***)

(** Output parity **)
Po[P_]:=Which[P==-1,"-",P==+1,"+"];

(** Dimension of basis **)
(* Two possible definitions for a single kind of boson *)
dimb1[ls_,n_,J_]:=Sum[multiplicity[ls[[1]],v,J],{v,Mod[n,2],n,2}];
dimb2[ls_,n_,J_]:=nstat1[1,{ls[[1]]},n,{J}];
(* Default *)
dimb[ls_,n_,J_]:=dimb2[ls,n,J]/; Length[ls]==1;
(* For several kinds of bosons *)
dimb[ls_,n_,J_]:=nstat[1,Map[({1,#,{#}})&,ls],n,{J}];

(** Basis construction in U(2l1+1) x U(2l2+1) x ... x U(2lp+1) **)
(* Input:   
   ls={l1,l2,...,lp}: angular momenta of the bosons;
   ps={p1,p2,...,pp}: parities of the bosons.
   => If an s boson is present it should be the first entry l1.
   Nb: total number of bosons (including the s bosons);
   J: total angular momentum the states;
   P: parity of the states. *)
(* Output:
   {{{n1,v1,a1,J1,K1}1,{n2,v2,a2,J2,K2}1,...,{np,vp,ap,Jp,Kp}1},
    {{n1,v1,a1,J1,K1}2,{n2,v2,a2,J2,K2}2,...,{np,vp,ap,Jp,Kp}2},
    ....}
   where
   {ni,vi,ai,Ji} are the labels associated with boson i;
   Ki is the intermediate coupling from Ki-1 x Ji;
   K1=J1 and Kp=J. *)

basb[ls_,n_,J_]:=
Block[{l,basis},
l=ls[[1]];
basis={};
Do[Do[basis=Append[basis,{{n,v,a,J,J}}],
      {a,1,mulv[l,v,J]}],
   {v,Mod[n,2],n,2}];
basis]/; Length[ls]==1;

basb[ls_,n_]:=
Flatten[Table[basb[ls,n,J],{J,0,n*ls[[1]]}],2]/; Length[ls]==1;

basb[ls_,Nb_,J_]:=
Block[{lsp,lsp1,np1,bp,Jp,Ip1,Ip1s},
lsp={ls[[-1]]}; lsp1=Drop[ls,-1];
Flatten[
Table[np1=Nb-np;
      bp=Map[Join[Drop[#,-1],{J}]&,basb[lsp,np]];
      Table[Jp=bp[[ip,4]];
            Ip1s=genang[{J},{Jp}];
            Table[Ip1=Ip1s[[ip1,1]];
                  Map[Join[#,{bp[[ip]]}]&,basb[lsp1,np1,Ip1]],
                  {ip1,1,Length[Ip1s]}],
            {ip,1,Length[bp]}],
      {np,0,Nb}],3]];

basb[ls_,ps_,Nb_,J_,P_]:=
Select[basb[ls,Nb,J],(Apply[Times,ps^(#[[All,1]])]==P)&];


(** List of all k-body scalar interactions **)
(* Notation: {{{n1c,v1c,a1c,L1c,I1c},{n2c,v2c,a2c,L2c,I2c},...,{npc,vpc,apc,Lpc,Ipc}},
              {{n1a,v1a,a1a,L1a,I1a},{n2a,v2a,a2a,L2a,I2a},...,{npa,vpa,apa,Lpa,Ipa}}}
             where c refers to the labels of the creation operator
                   a refers to the labels of the annihilation operator
                   k=n1c+n2c+...+npc=n1a+n2a+...+npa
             with L1c=I1c, L1a=I1a, Ipc=Ipa *)
genintAb[ls_,k_]:=
Block[{bk,dk,bkbk},
bk=Flatten[Table[basb[ls,k,Lk],{Lk,0,k*Max[ls]}],1]; dk=Length[bk];
bkbk=Flatten[Table[{bk[[i]],bk[[j]]},{i,1,dk},{j,1,dk}],1];
Which[k==0 || k==1,
      Table[{bk[[i]],bk[[i]]},{i,1,dk}],
      k>1,
      bkbk=Flatten[Table[{bk[[i]],bk[[j]]},{i,1,dk},{j,1,dk}],1];
      Select[bkbk,(#[[1,-1,-1]]==#[[2,-1,-1]])&]]];
(* Hermitian interactions *)
genintHb[ls_,k_]:=
Block[{bk,dk,bkbk},
bk=Flatten[Table[basb[ls,k,Lk],{Lk,0,k*Max[ls]}],1]; dk=Length[bk];
bkbk=Flatten[Table[{bk[[i]],bk[[j]]},{i,1,dk},{j,1,dk}],1];
Which[k==0 || k==1,
      Table[{bk[[i]],bk[[i]]},{i,1,dk}],
      k>1,
      bkbk=Flatten[Table[{bk[[i]],bk[[j]]},{i,1,dk},{j,i,dk}],1];
      Select[bkbk,(#[[1,-1,-1]]==#[[2,-1,-1]])&]]];
(* Parity-conserving interactions *)
genintAPb[ls_,ps_,k_]:=
Select[genintAb[ls,k],(Apply[Times,ps^(#[[1,All,1]])]==Apply[Times,ps^(#[[2,All,1]])])&];
(* Parity-conserving Hermitian interactions *)
genintHPb[ls_,ps_,k_]:=
Select[genintHb[ls,k],(Apply[Times,ps^(#[[1,All,1]])]==Apply[Times,ps^(#[[2,All,1]])])&];
(* Choose one as the default *)
genintb[ls_,k_]:=genintAb[ls,k];
genintb[ls_,ps_,k_]:=genintAPb[ls,ps,k];
(* Interactions in a simplified notation *)
genintsAb[ls_,k_]:=Map[vb[ls,#]&,genintAb[ls,k]];
genintsHb[ls_,k_]:=Map[vb[ls,#]&,genintHb[ls,k]];
genintsAPb[ls_,ps_,k_]:=Map[vb[ls,#]&,genintAPb[ls,ps,k]];
genintsHPb[ls_,ps_,k_]:=Map[vb[ls,#]&,genintHPb[ls,ps,k]];
genintsb[ls_,k_]:=Map[vb[ls,#]&,genintb[ls,k]];
genintsb[ls_,ps_,k_]:=Map[vb[ls,#]&,genintb[ls,ps,k]];

(** Matrix element of a scalar interaction **)
(* Matrix elements that are zero *)
(* kint is either the order of the interaction (a number)
   or it is an interaction element generated by genint;
   int is an interaction element generated by genint. *)
hmeb[ls_,kint_,bra_,ket_]:=0/; bra[[-1,5]]!=ket[[-1,5]];
(* Matrix element of a single scalar interaction term *)
hmeb[ls_,int_,bra_,ket_]:=0/; Length[int]!=0 && 
bra[[All,1]]-ket[[All,1]]!=int[[1,All,1]]-int[[2,All,1]];
hmeb[ls_,int_,bra_,ket_]:=0/; Length[int]!=0 && 
Apply[Or,Map[(#>0)&,Abs[bra[[All,2]]-ket[[All,2]]]-int[[1,All,2]]-int[[2,All,2]]]];
hmeb[ls_,int_,bra_,ket_]:=0/; Length[int]!=0 && 
Apply[Or,Map[(#>0)&,int[[1,All,1]]-bra[[All,1]]]] ||
Apply[Or,Map[(#>0)&,int[[2,All,1]]-ket[[All,1]]]];
hmeb[ls_,int_,bra_,ket_]:=0/; Length[int]!=0 && 
Apply[Plus,int[[1,All,1]]]<=1 && Apply[Plus,int[[2,All,1]]]<=1 && bra!=ket;
hmeb[ls_,int_,bra_,ket_]:=0/; Length[int]!=0 && 
Apply[Plus,int[[1,All,1]]]==Apply[Plus,bra[[All,1]]] && int[[1,-1,5]]!=bra[[-1,5]];

(* Matrix element of a k-body scalar interaction *)
hmeb[ls_,k_,bra_,ket_]:=
Block[{ints,di},
ints=genintb[ls,k]; di=Length[ints];
Sum[hmeb[ls,ints[[i]],bra,ket],{i,1,di}]]/; Length[k]==0;

(* Elimination of the s-boson dependence *)
hmeb[ls_,int_,bra_,ket_]:=
Sqrt[Binomial[bra[[1,1]],int[[1,1,1]]]*Binomial[ket[[1,1]],int[[2,1,1]]]]*
hmeb[Drop[ls,1],Map[Drop[#,1]&,int],Drop[bra,1],Drop[ket,1]]/; ls[[1]]==0;

(* Matrix element of a single scalar interaction term for a single l-boson *)
(* Notation: int={{{nc,vc,ac,Lc,Ic}},{{na,va,aa,La,Ia}}}
             with Lc=Ic=La=Ia;
             bra={{nb,vb,ab,Jb,Kb}}, ket={nk,vk,ak,Jk,Kk}
             with Jb=Kb=Jk=Kk. *)
hmeb[ls_,int_,bra_,ket_]:=
Block[{l,L,J,mc,vc,ac,ma,va,aa,nb,vb,ab,nk,vk,ak,ni,s},
l=ls[[1]]; L=int[[1,1,4]]; J=bra[[1,4]];
mc=int[[1,1,1]]; vc=int[[1,1,2]]; ac=int[[1,1,3]];
ma=int[[2,1,1]]; va=int[[2,1,2]]; aa=int[[2,1,3]];
nb=bra[[1,1]]; vb=bra[[1,2]]; ab=bra[[1,3]];
nk=ket[[1,1]]; vk=ket[[1,2]]; ak=ket[[1,3]];
ni=nb-mc;
s=Sum[cfps[l,ni,vi,ai,Li,mc,vc,ac,L,nb,vb,ab,J]*
      cfps[l,ni,vi,ai,Li,ma,va,aa,L,nk,vk,ak,J],
      {vi,Max[Abs[vb-vc],Abs[vk-va]],Min[ni,vb+vc,vk+va]},
      {Li,Abs[J-L],J+L},
      {ai,mulv[l,vi,Li]}];
redsqrtrat[Sqrt[Binomial[nb,mc]*Binomial[nk,ma]]*s]]/; Length[ls]==1;

(* General matrix element of a single scalar interaction term *)
(* Notation: int={{{n1c,v1c,a1c,L1c,I1c},{n2c,v2c,a2c,L2c,I2c},...,{npc,vpc,apc,Lpc,Ipc}},
                  {{n1a,v1a,a1a,L1a,I1a},{n2a,v2a,a2a,L2a,I2a},...,{npa,vpa,apa,Lpa,Ipa}}}
             with L1c=I1c, L1a=I1a, Ipc=Ipa;
             opep1={{{n1c,v1c,a1c,L1c,I1c},...,{np1c,vp1c,ap1c,Lp1c,Ip1c}},
                    {{n1a,v1a,a1a,L1a,I1a},...,{np1a,vp1a,ap1a,Lp1a,Ip1a}},R}
             opep={{{npc,vpc,apc,Lpc,Ipc}},{{npa,vpa,apa,Lpa,Ipa}},R}
             where c refers to the labels of the creation operator
                   a refers to the labels of the annihilation operator;
             bra={{n1b,v1b,a1b,J1b,K1b},{n2b,v2b,a2b,J2b,K2b},...,{npb,vpb,apb,Jpb,Kpb}}
             ket={{n1k,v1k,a1k,J1k,K1k},{n2k,v2k,a2k,J2k,K2k},...,{npk,vpk,apk,Jpk,Kpk}}
             with J1b=K1b, J1k=K1k, Kpb=Kpk;
             brap1={{n1b,v1b,a1b,J1b,K1b},...,{np1b,vp1b,ap1b,Jp1b,Kp1b}}
             ketp1={{n1k,v1k,a1k,J1k,K1k},...,{np1k,vp1k,ap1k,Jp1k,Kp1k}}
             brap={{npb,vpb,apb,Jpb,Kpb}}
             ketp={{npk,vpk,apk,Jpk,Kpk}}. *)
hmeb[ls_,int_,bra_,ket_]:=
Block[{lsp1,lsp,intp1,intp,opep1,opep,brap1,brap,ketp1,ketp,
       Ip1c,Ip1a,Lpc,Lpa,L,Kp1b,Kp1k,Jpb,Jpk,J,s},
lsp1=Drop[ls,-1]; intp1=Map[Drop[#,-1]&,int];
brap1=Drop[bra,-1]; ketp1=Drop[ket,-1];
lsp=Take[ls,-1];
intp=Map[{#[[-1,{1,2,3,4,4}]]}&,int];
brap={bra[[-1,{1,2,3,4,4}]]}; ketp={ket[[-1,{1,2,3,4,4}]]};
Ip1c=int[[1,-2,5]]; Ip1a=int[[2,-2,5]];
Lpc=int[[1,-1,4]]; Lpa=int[[2,-1,4]]; L=int[[1,-1,5]];
Kp1b=bra[[-2,5]]; Kp1k=ket[[-2,5]];
Jpb=bra[[-1,4]]; Jpk=ket[[-1,4]]; J=bra[[-1,5]];
s=Sum[opep1=Join[intp1,{R}]; opep=Join[intp,{R}];
      racah[Ip1c,Lpc,L,Lpa,Ip1a,R]*racah[Kp1b,Jpb,J,Jpk,Kp1k,R]*
      tmeb[lsp1,opep1,brap1,ketp1]*tmeb[lsp,opep,brap,ketp],
      {R,Max[Abs[Ip1c-Ip1a],Abs[Lpc-Lpa],Abs[Kp1b-Kp1k],Abs[Jpb-Jpk]],
         Min[Ip1c+Ip1a,Lpc+Lpa,Kp1b+Kp1k,Jpb+Jpk]}];
redsqrtrat[(-1)^(Kp1k+Jpb+Ip1a+Lpc+L+J)*(2*L+1)*s]];

(** Reduced matrix element of an operator **)
(* Reduced matrix elements that are zero *)
tmeb[ls_,ope_,bra_,ket_]:=0/; !trian[ope[[3]],bra[[-1,5]],ket[[-1,5]]];
tmeb[ls_,ope_,bra_,ket_]:=0/;
bra[[All,1]]-ket[[All,1]]!=ope[[1,All,1]]-ope[[2,All,1]];
tmeb[ls_,ope_,bra_,ket_]:=0/;
Apply[Or,Map[(#>0)&,Abs[bra[[All,2]]-ket[[All,2]]]-ope[[1,All,2]]-ope[[2,All,2]]]];
tmeb[ls_,ope_,bra_,ket_]:=0/;
Apply[Or,Map[(#>0)&,ope[[1,All,1]]-bra[[All,1]]]] ||
Apply[Or,Map[(#>0)&,ope[[2,All,1]]-ket[[All,1]]]];

(* Elimination of the s-boson dependence *)
tmeb[ls_,ope_,bra_,ket_]:=
Sqrt[Binomial[bra[[1,1]],ope[[1,1,1]]]*Binomial[ket[[1,1]],ope[[2,1,1]]]]*
tmeb[Drop[ls,1],Join[Map[Drop[#,1]&,ope[[{1,2}]]],{ope[[-1]]}],Drop[bra,1],Drop[ket,1]]/; ls[[1]]==0;

(* Reduced matrix element for a single l-boson *)
(* Notation: ope={{{nc,vc,ac,Lc,Ic}},{{na,va,aa,La,Ia}},R}
             with Lc=Ic, La=Ia;
             bra={{nb,vb,ab,Jb,Kb}}, ket={{nk,vk,ak,Jk,Kk}}
             with Jb=Kb, Jk=Kk. *)
tmeb[ls_,ope_,bra_,ket_]:=
Block[{l,R,nc,vc,ac,Lc,na,va,aa,La,nb,vb,ab,Jb,nk,vk,ak,Jk,ni,s},
l=ls[[1]]; R=ope[[3]];
nc=ope[[1,1,1]]; vc=ope[[1,1,2]]; ac=ope[[1,1,3]]; Lc=ope[[1,1,4]];
na=ope[[2,1,1]]; va=ope[[2,1,2]]; aa=ope[[2,1,3]]; La=ope[[2,1,4]];
nb=bra[[1,1]]; vb=bra[[1,2]]; ab=bra[[1,3]]; Jb=bra[[1,4]];
nk=ket[[1,1]]; vk=ket[[1,2]]; ak=ket[[1,3]]; Jk=ket[[1,4]];
ni=nb-nc;
s=Sum[(-1)^Ji*racah[Lc,La,R,Jk,Jb,Ji]*
      cfps[l,ni,vi,ai,Ji,nc,vc,ac,Lc,nb,vb,ab,Jb]*
      cfps[l,ni,vi,ai,Ji,na,va,aa,La,nk,vk,ak,Jk],
      {vi,Max[Abs[vb-vc],Abs[vk-va]],Min[ni,vb+vc,vk+va]},
      {Ji,Max[Abs[Jb-Lc],Abs[Jk-La]],Min[Jb+Lc,Jk+La]},
      {ai,mulv[l,vi,Ji]}];
redsqrtrat[(-1)^(Jb+La+R)*Sqrt[(2*Jb+1)*(2*R+1)*(2*Jk+1)*
           Binomial[nb,nc]*Binomial[nk,na]]*s]]/; Length[ls]==1;

(* General reduced matrix element *)
(* Notation: ope={{{n1c,v1c,a1c,L1c,I1c},{n2c,v2c,a2c,L2c,I2c},...,{npc,vpc,apc,Lpc,Ipc}},
                  {{n1a,v1a,a1a,L1a,I1a},{n2a,v2a,a2a,L2a,I2a},...,{npa,vpa,apa,Lpa,Ipa}},R}
             with L1c=I1c, L1a=I1a;
             opep1={{{n1c,v1c,a1c,L1c,I1c},...,{np1c,vp1c,ap1c,Lp1c,Ip1c}},
                    {{n1a,v1a,a1a,L1a,I1a},...,{np1a,vp1a,ap1a,Lp1a,Ip1a}},Rp1}
             opep={{{npc,vpc,apc,Lpc,Ipc}},{{npa,vpa,apa,Lpa,Ipa}},Rp}
             where c refers to the labels of the creation operator
                   a refers to the labels of the annihilation operator;
             bra={{n1b,v1b,a1b,J1b,K1b},{n2b,v2b,a2b,J2b,K2b},...,{npb,vpb,apb,Jpb,Kpb}}
             ket={{n1k,v1k,a1k,J1k,K1k},{n2k,v2k,a2k,J2k,K2k},...,{npk,vpk,apk,Jpk,Kpk}}
             with J1b=K1b, J1k=K1k;
             brap1={{n1b,v1b,a1b,J1b,K1b},...,{np1b,vp1b,ap1b,Jp1b,Kp1b}}
             ketp1={{n1k,v1k,a1k,J1k,K1k},...,{np1k,vp1k,ap1k,Jp1k,Kp1k}}
             brap={{npb,vpb,apb,Jpb,Kpb}}
             ketp={{npk,vpk,apk,Jpk,Kpk}}. *)
tmeb[ls_,ope_,bra_,ket_]:=
Block[{R,lsp1,lsp,intp1,intp,opep1,opep,brap1,brap,ketp1,ketp,
       Ip1c,Ip1a,Ipc,Ipa,Lpc,Lpa,Kp1b,Kp1k,Kpb,Kpk,Jpb,Jpk,s},
(* Print["  ls=",ls]; Print["  ope=",ope]; Print["  bra=",bra]; Print["  ket=",ket]; *)
R=ope[[3]];
lsp1=Drop[ls,-1]; intp1=Map[Drop[#,-1]&,ope[[{1,2}]]];
brap1=Drop[bra,-1]; ketp1=Drop[ket,-1];
lsp=Take[ls,-1];
intp=Map[{#[[-1,{1,2,3,4,4}]]}&,ope[[{1,2}]]];
brap={bra[[-1,{1,2,3,4,4}]]}; ketp={ket[[-1,{1,2,3,4,4}]]};
Ip1c=ope[[1,-2,5]]; Ip1a=ope[[2,-2,5]];
Lpc=ope[[1,-1,4]]; Lpa=ope[[2,-1,4]]; Ipc=ope[[1,-1,5]]; Ipa=ope[[2,-1,5]];
Kp1b=bra[[-2,5]]; Kp1k=ket[[-2,5]];
Kpb=bra[[-1,5]]; Kpk=ket[[-1,5]]; Jpb=bra[[-1,4]]; Jpk=ket[[-1,4]];
s=Sum[opep1=Join[intp1,{Rp1}]; opep=Join[intp,{Rp}];
(*Print["   lsp1=",lsp1];
Print["   opep1=",opep1,"; Ip1c=",Ip1c,"; Ip1a=",Ip1a];
Print["   brap1=",brap1,"; Kp1b=",Kp1b];
Print["   ketp1=",ketp1,"; Kp1k=",Kp1k];
Print["   lsp=",lsp];
Print["   opep=",opep,"; Lpc=",Lpc,"; Lpa=",Lpa,"; Ipc=",Ipc,"; Ipa=",Ipa];
Print["   brap=",brap,"; Kpb=",Kpb,"; Jpb=",Jpb];
Print["   ketp=",ketp,"; Kpk=",Kpk,"; Jpk=",Jpk];
Print["   ",Ip1c," ",Lpc," ",Ipc," ",Ip1a," ",Lpa," ",Ipa," ",Rp1," ",Rp," ",R];
Print["   ninej1=",ninej[Ip1c,Lpc,Ipc,Ip1a,Lpa,Ipa,Rp1,Rp,R]];
Print["   ",Kp1b," ",Jpb," ",Kpb," ",Kp1k," ",Jpk," ",Kpk," ",Rp1," ",Rp," ",R];
Print["   ninej2=",ninej[Kp1b,Jpb,Kpb,Kp1k,Jpk,Kpk,Rp1,Rp,R]];*)     
      Sqrt[(2*Rp1+1)*(2*Rp+1)]*
      ninej[Ip1c,Lpc,Ipc,Ip1a,Lpa,Ipa,Rp1,Rp,R]*
      ninej[Kp1b,Jpb,Kpb,Kp1k,Jpk,Kpk,Rp1,Rp,R]*
      tmeb[lsp1,opep1,brap1,ketp1]*tmeb[lsp,opep,brap,ketp],
      {Rp1,Max[Abs[Ip1c-Ip1a],Abs[Kp1b-Kp1k]],Min[Ip1c+Ip1a,Kp1b+Kp1k]},
      {Rp,Max[Abs[Lpc-Lpa],Abs[Jpb-Jpk],Abs[Rp1-R]],Min[Lpc+Lpa,Jpb+Jpk,Rp1+R]}];
redsqrtrat[Sqrt[(2*Ipc+1)*(2*Ipa+1)*(2*Kpb+1)*(2*Kpk+1)*(2*R+1)]*s]];

(** Hamiltonian matrix for all possible k-body interactions **)
hamsqb[ls_,k_,Nb_,J_]:=
Block[{ints,di,bn,dn},
ints=genintb[ls,k]; di=Length[ints];
bn=basb[ls,Nb,J]; dn=Length[bn];
Table[Sum[vb[ls,ints[[i]]]*hmeb[ls,ints[[i]],bn[[ib]],bn[[ik]]],{i,1,di}],{ib,1,dn},{ik,1,dn}]];
hamb[ls_,k_,Nb_,J_]:=
hamb[ls,k,Nb,J]=
Block[{ints,di,bn,dn},
ints=genintb[ls,k]; di=Length[ints];
bn=basb[ls,Nb,J]; dn=Length[bn];
Flatten[Table[Sum[vb[ls,ints[[i]]]*hmeb[ls,ints[[i]],bn[[ib]],bn[[ik]]],{i,1,di}],
              {ib,1,dn},{ik,ib,dn}],1]];
hamb[ls_,ps_,k_,Nb_,J_,P_]:=
hamb[ls,ps,k,Nb,J,P]=
Block[{ints,di,bn,dn},
ints=genintb[ls,ps,k]; di=Length[ints];
bn=basb[ls,ps,Nb,J,P]; dn=Length[bn];
Flatten[Table[Sum[vb[ls,ints[[i]]]*hmeb[ls,ints[[i]],bn[[ib]],bn[[ik]]],{i,1,di}],
              {ib,1,dn},{ik,ib,dn}],1]];
      
(** Hamiltonian matrix for a single interaction **)
hovb[ls_,Nb_,J_,int_]:=
(*hovb[ls,Nb,J,int]=*)
Block[{bn,dn},
bn=basb[ls,Nb,J]; dn=Length[bn];
Flatten[Table[hmeb[ls,int,bn[[ib]],bn[[ik]]],{ib,1,dn},{ik,ib,dn}],1]];
hovb[ls_,ps_,Nb_,J_,P_,int_]:=
(*hovb[ls,ps,Nb,J,P,int]=*)
Block[{bn,dn},
bn=basb[ls,ps,Nb,J,P]; dn=Length[bn];
Flatten[Table[hmeb[ls,int,bn[[ib]],bn[[ik]]],{ib,1,dn},{ik,ib,dn}],1]];

(** Hamiltonian matrix for one operator **)
hopsqb[ls_,Nb_,J_,hop_]:=
Block[{bn,dn,c2},
bn=basb[ls,Nb,J]; dn=Length[bn];
If[hop===c22su3sd,
   c2=hopsqb[ls,Nb,J,c2su3sd]; c2 . c2,
   Table[hop[ls,bn[[ib]],bn[[ik]]],{ib,1,dn},{ik,1,dn}]]];
hopb[ls_,Nb_,J_,hop_]:=
(*hopb[ls,Nb,J,hop]=*)
Block[{bn,dn,c2,c22},
bn=basb[ls,Nb,J]; dn=Length[bn];
If[hop===c22su3sd,
   c2=hopb[ls,Nb,J,c2su3sd]; c22=sqh[c2] . sqh[c2];
   Flatten[Table[c22[[ib,ik]],{ib,1,dn},{ik,ib,dn}],1],
   Flatten[Table[hop[ls,bn[[ib]],bn[[ik]]],{ib,1,dn},{ik,ib,dn}],1]]];
hopb[ls_,ps_,Nb_,J_,P_,hop_]:=
(*hopb[ls,ps,Nb,J,P,hop]=*)
Block[{bn,dn},
bn=basb[ls,ps,Nb,J,P]; dn=Length[bn];
Flatten[Table[hop[ls,bn[[ib]],bn[[ik]]],{ib,1,dn},{ik,ib,dn}],1]];

(** Hamiltonian matrix for a combination of operators and interactions **)
(* hops is an array {{cf1,operator1},...} 
   where cfi is a coefficient in front of operatori
   ints is an array {{cf1,int1},...} *)
(* With multipole-to-normal-order conversion *)
hopvb1[ls_,Nb_,J_,hops_,ints_]:=
Block[{kmax,conv},
kmax=Max[Map[order,hops[[All,2]]]];
conv=multonorb[ls,hops];
Sum[hamb[ls,k,Nb,J],{k,0,kmax}]/.conv]+
Sum[ints[[i,1]]*hovb[ls,Nb,J,ints[[i,2]]],{i,1,Length[ints]}];
hopvb1[ls_,ps_,Nb_,J_,P_,hops_,ints_]:=
Block[{kmax,conv},
kmax=Max[Map[order,hops[[All,2]]]];
conv=multonorb[ls,hops];
Sum[hamb[ls,ps,k,Nb,J,P],{k,0,kmax}]/.conv]+
Sum[ints[[i,1]]*hovb[ls,ps,Nb,J,P,ints[[i,2]]],{i,1,Length[ints]}];
(* Without multipole-to-normal-order conversion *)
hopvb2[ls_,Nb_,J_,hops_,ints_]:=
Sum[hops[[i,1]]*hopb[ls,Nb,J,hops[[i,2]]],{i,1,Length[hops]}]+
Sum[ints[[i,1]]*hovb[ls,Nb,J,ints[[i,2]]],{i,1,Length[ints]}];
hopvb2[ls_,ps_,Nb_,J_,P_,hops_,ints_]:=
Sum[hops[[i,1]]*hopb[ls,ps,Nb,J,P,hops[[i,2]]],{i,1,Length[hops]}]+
Sum[ints[[i,1]]*hovb[ls,ps,Nb,J,P,ints[[i,2]]],{i,1,Length[ints]}];
(* Choose one as the default *)
hopvb[ls_,Nb_,J_,hops_,ints_]:=hopvb1[ls,Nb,J,hops,ints];
hopvb[ls_,ps_,Nb_,J_,P_,hops_,ints_]:=hopvb1[ls,ps,Nb,J,P,hops,ints];

(** Spectrum of a linear combination of multipole operators and interactions **)
(* n eigenstates for the angular momenta in Js.
   c=1: prints n eigenvalues relative to the J=0 ground state
   c=2: + eigenvector of yrast states
   c=3: + n eigenvectors
   c=4: outputs n eigenvalues and eigenvectors *)
specb[ls_,Nb_,Js_,n_,hops_,ints_,c_]:=
Block[{tab,J,ham,eig,egs,dim,nd},
egs=0;
tab=Table[J=Js[[i]];
          ham=sqh[hopvb[ls,Nb,J,hops,ints]];
          dim=Length[ham]; nd=Min[n,dim];
          If[dim==0,{},
             eig=Map[Take[#,nd]&,eigensystem[ham]];
             If[J==0,egs=eig[[1,1]]; Print["Ground-state energy: ",egs]];
             If[c==1||c==2||c==3,Print["J=",J," (dim=",dim,") Energies: ",Take[eig[[1]]-egs,nd]]];
             If[c==2,Print["Eigenvector yrast state: ",eig[[2,1]]]];
             If[c==3,Do[Print["Eigenvector state ",j,": ",eig[[2,j]]],{j,1,nd}]];
             If[c==4,Print["J=",J," (dim=",dim,") Energies: ",Take[eig[[1]],nd]]];
             eig],
          {i,1,Length[Js]}];
If[c==4,tab]];
specb[ls_,ps_,Nb_,Js_,Ps_,n_,hops_,ints_,c_]:=
Block[{tab,J,P,sP,ham,eig,egs,dim,nd},
egs=0;
tab=Table[J=Js[[i]]; P=Ps[[i]]; sP=Which[P==1,"+",P==-1,"-"];
          ham=sqh[hopvb[ls,ps,Nb,J,P,hops,ints]];
          dim=Length[ham]; nd=Min[n,dim];
          If[dim==0,{},
             eig=Map[Take[#,nd]&,eigensystem[ham]];
             If[J==0 && P==1,egs=eig[[1,1]]; Print["Ground-state energy: ",egs]];
             If[c==1||c==2||c==3,Print["J=",J,sP," (dim=",dim,") Energies: ",Take[eig[[1]]-egs,nd]]];
             If[c==2,Print["Eigenvector yrast state: ",eig[[2,1]]]];
             If[c==3,Do[Print["Eigenvector state ",j,": ",eig[[2,j]]],{j,1,nd}]];
             If[c==4,Print["J=",J,sP," (dim=",dim,") Energies: ",Take[eig[[1]],nd]]];
             eig],
   {i,1,Length[Js]}];
If[c==4,tab]];

(** Transition matrices **)
(* Of an operator in the basis basb *)
topb[ls_,Nbi_,Ji_,Nbf_,Jf_,top_]:=
Block[{bni,dni,bnf,dnf},
bni=basb[ls,Nbi,Ji]; dni=Length[bni];
bnf=basb[ls,Nbf,Jf]; dnf=Length[bnf];
Table[top[ls,bnf[[ib]],bni[[ik]]],{ib,1,dnf},{ik,1,dni}]];
topb[ls_,ps_,Nbi_,Ji_,Pi_,Nbf_,Jf_,Pf_,top_]:=
Block[{bni,dni,bnf,dnf},
bni=basb[ls,ps,Nbi,Ji,Pi]; dni=Length[bni];
bnf=basb[ls,ps,Nbf,Jf,Pf]; dnf=Length[bnf];
Table[top[ls,bnf[[ib]],bni[[ik]]],{ib,1,dnf},{ik,1,dni}]];

(* Of an operator between eigenstates of hops+ints *)
tranb[ls_,Nbi_,Ji_,ni_,Nbf_,Jf_,nf_,hops_,ints_,top_]:=
Block[{eigi,eni,wai,eigf,enf,waf,tmat,trans},
eigi=eigensystem[sqh[hopvb[ls,Nbi,Ji,hops,ints]]];
eni=Take[eigi[[1]],ni]; wai=Take[eigi[[2]],ni];
eigf=eigensystem[sqh[hopvb[ls,Nbf,Jf,hops,ints]]];
enf=Take[eigf[[1]],nf]; waf=Take[eigf[[2]],nf];
tmat=topb[ls,Nbi,Ji,Nbf,Jf,top];
trans=Simplify[waf . tmat . Transpose[wai]];
Do[Print["<",Jf,"(",if,";",enf[[if]],")||",top,"||",
         Ji,"(",ii,";",eni[[ii]],")>=",trans[[if,ii]]],
   {if,1,nf},{ii,1,ni}]];
tranb[ls_,ps_,Nbi_,Ji_,Pi_,ni_,Nbf_,Jf_,Pf_,nf_,hops_,ints_,top_]:=
Block[{sPi,eigi,eni,wai,sPf,eigf,enf,waf,tmat,trans},
sPi=Which[Pi==1,"+",Pi==-1,"-"]; sPf=Which[Pf==1,"+",Pf==-1,"-"]; 
eigi=eigensystem[sqh[hopvb[ls,ps,Nbi,Ji,Pi,hops,ints]]];
eni=Take[eigi[[1]],ni]; wai=Take[eigi[[2]],ni];
eigf=eigensystem[sqh[hopvb[ls,ps,Nbf,Jf,Jf,hops,ints]]];
enf=Take[eigf[[1]],nf]; waf=Take[eigf[[2]],nf];
tmat=topb[ls,ps,Nbi,Ji,Pi,Nbf,Jf,Pf,top];
trans=Simplify[waf . tmat . Transpose[wai]];
Do[Print["<",Jf,sPf,"(",if,";",enf[[if]],")||",top,"||",
         Ji,sPi,"(",ii,";",eni[[ii]],")>=",trans[[if,ii]]],
   {if,1,nf},{ii,1,ni}]];

(* Electromagnetic transitions *)
(* Calculates transitions from Ji(1 to ni) to Jf(1 to nf)
   c=1: reduced transition matrix elements
   c=2: B(E or M) values
   c=3: outputs reduced matrix elements *)
emtrb[ls_,Nb_,Ji_,ni_,Jf_,nf_,hops_,ints_,top_,c_]:=
Block[{eigi,eigf,tmat,tem},
eigi=specb[ls,Nb,{Ji},ni,hops,ints,4][[1]];
eigf=specb[ls,Nb,{Jf},nf,hops,ints,4][[1]];
tmat=topb[ls,Nb,Ji,Nb,Jf,top];
tem=Chop[Simplify[eigf[[2]] . tmat . Transpose[eigi[[2]]]]];
Which[
c==1,Do[Print["<",Jf,"(",if,")||",top,"||",Ji,"(",ii,")>=",tem[[if,ii]]],
       {if,1,nf},{ii,1,ni}],
c==2,Do[Print["B[",top,";",Ji,"(",ii,")->",Jf,"(",if,")]=",tem[[if,ii]]^2/(2*Ji+1)],
       {if,1,nf},{ii,1,ni}],
c==3,tem]];
emtrb[ls_,ps_,Nb_,Ji_,Pi_,ni_,Jf_,Pf_,nf_,hops_,ints_,top_,c_]:=
Block[{sPi,eigi,sPf,eigf,tmat,tem},
sPi=Which[Pi==1,"+",Pi==-1,"-"]; sPf=Which[Pf==1,"+",Pf==-1,"-"];
eigi=specb[ls,ps,Nb,{Ji},{Pi},ni,hops,ints,4][[1]];
eigf=specb[ls,ps,Nb,{Jf},{Pf},nf,hops,ints,4][[1]];
tmat=topb[ls,ps,Nb,Ji,Pi,Nb,Jf,Pf,top];
tem=Chop[Simplify[eigf[[2]] . tmat . Transpose[eigi[[2]]]]];
Which[
c==1,Do[Print["<",Jf,sPf,"(",if,")||",top,"||",Ji,sPi,"(",ii,")>=",tem[[if,ii]]],
       {if,1,nf},{ii,1,ni}],
c==2,Do[Print["B[",top,";",Ji,sPi,"(",ii,")->",Jf,sPf,"(",if,")]=",tem[[if,ii]]^2/(2*Ji+1)],
       {if,1,nf},{ii,1,ni}],
c==3,tem]];

(* Electromagnetic moments *)
(* Calculates the moments of J(1 to n)
   c=1: reduced matrix elements
   c=2: moments
   c=3: outputs reduced matrix elements *)
emmob[ls_,Nb_,J_,n_,hops_,ints_,top_,c_]:=
Block[{eig,tmat,tem},
eig=specb[ls,Nb,{J},n,hops,ints,4][[1]];
tmat=topb[ls,Nb,J,Nb,J,top];
tem=Chop[Simplify[eig[[2]] . tmat . Transpose[eig[[2]]]]];
Which[
c==1,Do[Print["<",J,"(",i,")||",top,"||",J,"(",i,")>=",tem[[i,i]]],{i,1,n}],
c==2 && top===obM1,Do[Print["\[Mu][",J,"(",i,")]=",Sqrt[4*Pi/3]*wigner[J,1,J,-J,0,J]*tem[[i,i]]],{i,1,n}],
c==2 && top===obE2,Do[Print["Q[",J,"(",i,")]=",Sqrt[16*Pi/5]*wigner[J,2,J,-J,0,J]*tem[[i,i]]],{i,1,n}],
c==3,tem]];
emmob[ls_,ps_,Nb_,J_,P_,n_,hops_,ints_,top_,c_]:=
Block[{sP,eig,tmat,tem},
sP=Which[P==1,"+",P==-1,"-"];
eig=specb[ls,ps,Nb,{J},{P},n,hops,ints,4][[1]];
tmat=topb[ls,ps,Nb,J,P,Nb,J,P,top];
tem=Chop[Simplify[eig[[2]] . tmat . Transpose[eig[[2]]]]];
Which[
c==1,Do[Print["<",J,sP,"(",i,")||",top,"||",J,sP,"(",i,")>=",tem[[i,i]]],{i,1,n}],
c==2 && top==obM1,Do[Print["\[Mu][",J,sP,"(",i,")]=",Sqrt[4*Pi/3]*wigner[J,1,J,-J,0,J]*tem[[i,i]]],{i,1,n}],
c==2 && top==obE2,Do[Print["Q[",J,sP,"(",i,")]=",Sqrt[16*Pi/5]*wigner[J,2,J,-J,0,J]*tem[[i,i]]],{i,1,n}],
c==3,tem]];

(** Reduced matrix element of a boson creation or annihilation operator **)
(* Reduced matrix element of b(lc)+ *)
rmebcb[ls_,ic_,bra_,ket_]:=0/; bra[[ic,1]]==0;
rmebcb[ls_,ic_,bra_,ket_]:=0/; bra[[All,1]]-Table[delta[i,ic],{i,1,Length[ls]}]!=ket[[All,1]];
rmebcb[ls_,ic_,bra_,ket_]:=
(* rmebcb[ls,ic,bra,ket]= *)
Block[{p,lc,topc,topa},
p=Length[ls]; lc=ls[[ic]]; 
topc=Table[Which[i<ic,{0,0,1,0,0},i==ic,{1,1,1,lc,lc},i>ic,{0,0,1,0,lc}],{i,1,p}];
topa=Table[{0,0,1,0,0},{i,1,p}];
tmeb[ls,{topc,topa,lc},bra,ket]];
(* Reduced matrix element of b(la) *)
rmebab[ls_,ia_,bra_,ket_]:=0/; ket[[ia,1]]==0;
rmebab[ls_,ia_,bra_,ket_]:=0/; bra[[All,1]]!=ket[[All,1]]-Table[delta[i,ia],{i,1,Length[b1j]}];
rmebab[ls_,ia_,bra_,ket_]:=
(* rmebab[ls,ia,bra,ket]= *)
Block[{p,la,topc,topa},
p=Length[ls]; la=ls[[ia]]; 
topc=Table[{0,0,1,0,0},{i,1,p}];
topa=Table[Which[i<ia,{0,0,1,0,0},i==ia,{1,1,1,la,la},i>ia,{0,0,1,0,la}],{i,1,p}];
tmeb[ls,{topc,topa,la},bra,ket]];

(** Reduced matrix element of a combination of bilinear operators T^(lambda)[top] **)
(* tops contains the sequence {top1,top2,...} where top defines the operator
   T^(lambda)[top] = \sum_{lc,la} acb^(top,lambda,ic,ia) [b+(ic) b(ia)]^(lambda),
   where the coefficients acb^(top,lambda,ic,ia) are predefined;
   lambdas contains the sequence {lambda1,lambda2,...};
   Lambdas contains the sequence {Lambda1=lambda1,Lambda2,...,Lambdan}.
   bra={{n1b,v1b,a1b,J1b,K1b},{n2b,v2b,a2b,J2b,K2b},...,{npb,vpb,apb,Jpb,Kpb}}
   ket={{n1k,v1k,a1k,J1k,K1k},{n2k,v2k,a2k,J2k,K2k},...,{npk,vpk,apk,Jpk,Kpk}} *)

(* The ac coefficients satisfy the triangular condition. *)
acb[ls_,top_,lambda_,ic_,ia_]:=0/; !trian[lambda,ls[[ic]],ls[[ia]]];

(* Some conditions for a zero reduced matrix element *)
rmeTb[ls_,tops_,lambdas_,Lambdas_,bra_,ket_]:=0/;
!trian[Lambdas[[-1]],bra[[-1,5]],ket[[-1,5]]];
rmeTb[ls_,tops_,lambdas_,Lambdas_,bra_,ket_]:=0/;
Apply[Plus,bra[[All,1]]]!=Apply[Plus,ket[[All,1]]];
rmeTb[ls_,tops_,lambdas_,Lambdas_,bra_,ket_]:=0/;
Apply[Or,Map[(#<0)&,Length[lambdas]-Abs[bra[[All,1]]-ket[[All,1]]]]];
rmeTb[ls_,tops_,lambdas_,Lambdas_,bra_,ket_]:=0/;
Apply[Or,Map[(#<0)&,2*Length[lambdas]-Abs[bra[[All,2]]-ket[[All,2]]]]];

(* Reduced matrix element of a series of T^(lambda)[r] *)
rmeTb[ls_,tops_,lambdas_,Lambdas_,bra_,ket_]:=
Block[{Nb,Jb,Jk,top,lambdak,Lambdak,Lambdak1,Tlast,ints,int,s},
Nb=Apply[Plus,bra[[All,1]]]; Jb=bra[[-1,5]]; Jk=ket[[-1,5]];
lambdak=lambdas[[-1]]; top=tops[[-1]]; Lambdak=Lambdas[[-1]]; Lambdak1=Lambdas[[-2]];
s=Sum[ints=basb[ls,Nb,Ji];
      Sum[int=ints[[i]];
          Tlast=rmeTb[ls,{top},{lambdak},{lambdak},int,ket];
          If[Tlast===0,0,
             racah[Lambdak1,lambdak,Lambdak,Jk,Jb,Ji]*Tlast*
             rmeTb[ls,Drop[tops,-1],Drop[lambdas,-1],Drop[Lambdas,-1],bra,int]],
          {i,1,Length[ints]}],
      {Ji,Max[Abs[Lambdak1-Jb],Abs[lambdak-Jk]],Min[Lambdak1+Jb,lambdak+Jk]}];
(-1)^(Jb+Jk+Lambdak)*Sqrt[2*Lambdak+1]*s]/; Length[lambdas]>1;

(* Reduced matrix element of a single T^(lambda)[r] *) 
rmeTb[ls_,tops_,lambdas_,Lambdas_,bra_,ket_]:=
Block[{p,lambda,top},
p=Length[ls]; lambda=lambdas[[1]]; top=tops[[1]];
Sum[If[acb[ls,top,lambda,ic,ia]===0,0,
       acb[ls,top,lambda,ic,ia]*rmeT1b[ls,ic,ia,lambda,bra,ket]],
       {ic,1,p},{ia,1,p}]]/; Length[lambdas]==1;

(* Reduced matrix element of (b(ic)+ b(ia))^(lambda) *)
rmeT1b[ls_,ic_,ia_,lambda_,bra_,ket_]:=0/;
bra[[All,1]]-Table[delta[i,ic],{i,1,Length[ls]}]!=
ket[[All,1]]-Table[delta[i,ia],{i,1,Length[ls]}];
rmeT1b[ls_,ic_,ia_,lambda_,bra_,ket_]:=
Block[{p,lc,la,opec,opea},
p=Length[ls]; lc=ls[[ic]]; la=ls[[ia]];
opec=Table[Which[i<ic,{0,0,1,0,0},i==ic,{1,1,1,lc,lc},i>ic,{0,0,1,0,lc}],{i,1,p}];
opea=Table[Which[i<ia,{0,0,1,0,0},i==ia,{1,1,1,la,la},i>ia,{0,0,1,0,la}],{i,1,p}];
tmeb[ls,{opec,opea,lambda},bra,ket]];

(** Matrix elements of tensor operators (hop or top) in multipole form **)
(* If the operator is a scalar(hop), the matrix element is calculated;
   otherwise (top), the reduced matrix element is calculated.
   obL is the angular momentum operator;
   obQ is a quadrupole operator;
   obO is an octupole operator;
   obH is a hexadecapole operator. *)
(* Scalar operators *)
obn1[ls_,bra_,ket_]:=delta[bra,ket]*bra[[1,1]];
obn2[ls_,bra_,ket_]:=delta[bra,ket]*bra[[2,1]];
obn3[ls_,bra_,ket_]:=delta[bra,ket]*bra[[3,1]];
obn4[ls_,bra_,ket_]:=delta[bra,ket]*bra[[4,1]];
obn1n1[ls_,bra_,ket_]:=2*delta[bra,ket]*bra[[1,1]]*bra[[1,1]];
obn1n2[ls_,bra_,ket_]:=delta[bra,ket]*bra[[1,1]]*bra[[2,1]];
obn2n2[ls_,bra_,ket_]:=2*delta[bra,ket]*bra[[2,1]]*bra[[2,1]];
obLL[ls_,bra_,ket_]:=delta[bra,ket]*bra[[-1,5]]*(bra[[-1,5]]+1);
obQQ[ls_,bra_,ket_]:=Sqrt[5]*rmeTb[ls,{obQ,obQ},{2,2},{2,0},bra,ket]/Sqrt[2*bra[[-1,5]]+1];
obOO[ls_,bra_,ket_]:=-Sqrt[7]*rmeTb[ls,{obO,obO},{3,3},{3,0},bra,ket]/Sqrt[2*bra[[-1,5]]+1];
obHH[ls_,bra_,ket_]:=Sqrt[9]*rmeTb[ls,{obH,obH},{4,4},{4,0},bra,ket]/Sqrt[2*bra[[-1,5]]+1];
obQQQ[ls_,bra_,ket_]:=rmeTb[ls,{obQ,obQ,obQ},{2,2,2},{2,2,0},bra,ket]/Sqrt[2*bra[[-1,5]]+1];
obLQQ[ls_,bra_,ket_]:=rmeTb[ls,{obL,obQ,obQ},{1,2,2},{1,2,0},bra,ket]/Sqrt[2*bra[[-1,5]]+1];
obQLQ[ls_,bra_,ket_]:=rmeTb[ls,{obQ,obL,obQ},{2,1,2},{2,2,0},bra,ket]/Sqrt[2*bra[[-1,5]]+1];
obQQL[ls_,bra_,ket_]:=rmeTb[ls,{obQ,obQ,obL},{2,2,1},{2,1,0},bra,ket]/Sqrt[2*bra[[-1,5]]+1];
obQLL[ls_,bra_,ket_]:=rmeTb[ls,{obQ,obL,obL},{2,1,1},{2,1,0},bra,ket]/Sqrt[2*bra[[-1,5]]+1];
obLQL[ls_,bra_,ket_]:=rmeTb[ls,{obL,obQ,obL},{1,2,1},{1,1,0},bra,ket]/Sqrt[2*bra[[-1,5]]+1];
obLLQ[ls_,bra_,ket_]:=rmeTb[ls,{obL,obL,obQ},{1,1,2},{1,2,0},bra,ket]/Sqrt[2*bra[[-1,5]]+1];
obLLL[ls_,bra_,ket_]:=rmeTb[ls,{obL,obL,obL},{1,1,1},{1,1,0},bra,ket]/Sqrt[2*bra[[-1,5]]+1];
obLL0LL[ls_,bra_,ket_]:=rmeTb[ls,{obL,obL,obL,obL},{1,1,1,1},{1,0,1,0},bra,ket]/Sqrt[2*bra[[-1,5]]+1];
obLL1LL[ls_,bra_,ket_]:=rmeTb[ls,{obL,obL,obL,obL},{1,1,1,1},{1,1,1,0},bra,ket]/Sqrt[2*bra[[-1,5]]+1];
obLL2LL[ls_,bra_,ket_]:=rmeTb[ls,{obL,obL,obL,obL},{1,1,1,1},{1,2,1,0},bra,ket]/Sqrt[2*bra[[-1,5]]+1];
obQQ0QQ[ls_,bra_,ket_]:=rmeTb[ls,{obQ,obQ,obQ,obQ},{2,2,2,2},{2,0,2,0},bra,ket]/Sqrt[2*bra[[-1,5]]+1];
obQQ1QQ[ls_,bra_,ket_]:=rmeTb[ls,{obQ,obQ,obQ,obQ},{2,2,2,2},{2,1,2,0},bra,ket]/Sqrt[2*bra[[-1,5]]+1];
obQQ2QQ[ls_,bra_,ket_]:=rmeTb[ls,{obQ,obQ,obQ,obQ},{2,2,2,2},{2,2,2,0},bra,ket]/Sqrt[2*bra[[-1,5]]+1];
obQQ3QQ[ls_,bra_,ket_]:=rmeTb[ls,{obQ,obQ,obQ,obQ},{2,2,2,2},{2,3,2,0},bra,ket]/Sqrt[2*bra[[-1,5]]+1];
obQQ4QQ[ls_,bra_,ket_]:=rmeTb[ls,{obQ,obQ,obQ,obQ},{2,2,2,2},{2,4,2,0},bra,ket]/Sqrt[2*bra[[-1,5]]+1];
obLQ1LQ[ls_,bra_,ket_]:=rmeTb[ls,{obL,obQ,obL,obQ},{1,1,2,0},bra,ket]/Sqrt[2*bra[[-1,5]]+1];
obLQ2LQ[ls_,bra_,ket_]:=rmeTb[ls,{obL,obQ,obL,obQ},{1,2,1,2},{1,2,2,0},bra,ket]/Sqrt[2*bra[[-1,5]]+1];
obLQ3LQ[ls_,bra_,ket_]:=rmeTb[ls,{obL,obQ,obL,obQ},{1,2,1,2},{1,3,2,0},bra,ket]/Sqrt[2*bra[[-1,5]]+1];
(* The order of the scalar operators in the generators must be declared *)
order[o_]:=1/; o==obn1 || o==obn2 || o==obn3 || o==obn4;
order[o_]:=2/; o==obn1n1 || o==obn1n2 || o==obn2n2 || o==obLL ||
               o==obQQ || o==obOO || o==obHH;
order[o_]:=3/; o==obQQQ || o==obLQQ || o==obQLQ || o==obQQL ||
               o==obQLL || o==obLQL || o==obLLQ || o==obLLL;
order[o_]:=4/; o==obQQ0QQ || o==obQQ1QQ || o==obQQ2QQ || o==obQQ3QQ || o==obQQ4QQ ||
               o==obLQ1LQ || o==obLQ2LQ || o==obLQ3LQ ||
               o==obLL0LL || o==obLL1LL || o==obLL2LL;
(* Non-scalar operators *)
obL[ls_,bra_,ket_]:=delta[bra,ket]*Sqrt[bra[[-1,5]]*(bra[[-1,5]]+1)*(2*bra[[-1,5]]+1)];
obE1[ls_,bra_,ket_]:=rmeTb[ls,{obE1},{1},{1},bra,ket];
obM1[ls_,bra_,ket_]:=Sqrt[3/(4*Pi)]*rmeTb[ls,{obM1},{1},{1},bra,ket];
obmu[ls_,bra_,ket_]:=rmeTb[ls,{obM1},{1},{1},bra,ket];
obQ[ls_,bra_,ket_]:=rmeTb[ls,{obQ},{2},{2},bra,ket];
obQa[ls_,bra_,ket_]:=rmeTb[ls,{obQa},{2},{2},bra,ket];
obQb[ls_,bra_,ket_]:=rmeTb[ls,{obQb},{2},{2},bra,ket];
obE2[ls_,bra_,ket_]:=rmeTb[ls,{obE2},{2},{2},bra,ket];
obq[ls_,bra_,ket_]:=Sqrt[16*Pi/5]*rmeTb[ls,{obE2},{2},{2},bra,ket];
obO[ls_,bra_,ket_]:=rmeTb[ls,{obO},{3},{3},bra,ket];
obH[ls_,bra_,ket_]:=rmeTb[ls,{obH},{4},{4},bra,ket];
obLL1[ls_,bra_,ket_]:=rmeTb[ls,{obL,obL},{1,1},{1,1},bra,ket];
obLL2[ls_,bra_,ket_]:=rmeTb[ls,{obL,obL},{1,1},{1,2},bra,ket];
obLQ1[ls_,bra_,ket_]:=rmeTb[ls,{obL,obQ},{1,2},{1,1},bra,ket];
obLQ2[ls_,bra_,ket_]:=rmeTb[ls,{obL,obQ},{1,2},{1,2},bra,ket];
obLQ3[ls_,bra_,ket_]:=rmeTb[ls,{obL,obQ},{1,2},{1,3},bra,ket];
obQQ1[ls_,bra_,ket_]:=rmeTb[ls,{obQ,obQ},{2,2},{2,1},bra,ket];
obQQ2[ls_,bra_,ket_]:=rmeTb[ls,{obQ,obQ},{2,2},{2,2},bra,ket];
obQQ3[ls_,bra_,ket_]:=rmeTb[ls,{obQ,obQ},{2,2},{2,3},bra,ket];
obQQ4[ls_,bra_,ket_]:=rmeTb[ls,{obQ,obQ},{2,2},{2,4},bra,ket];

(** From multipole to normal-order representation **)
(* ops is an array {{cf1,operator1},...} 
   where cfi is a coefficient in front of operatori *)
multonorb[ls_,ops_]:=
(*multonorb[ls,ops]=*)
Block[{lmax,ors,ormax,kmax,ints,intsmax,intsrest,unks,ev,evr,hmul,hnor},
lmax=Max[ls]; ors=Map[order,ops[[All,2]]]; ormax=Max[ors];
intsmax=Flatten[Table[genintAb[ls,k],{k,0,ormax}],1];
ev=Table[vb[ls,intsmax[[i]]]->0,{i,1,Length[intsmax]}];
Do[kmax=ors[[r]];
   ints=Flatten[Table[genintAb[ls,k],{k,0,kmax}],1];
   unks=Table[vb[ls,ints[[i]]],{i,1,Length[ints]}];
   hmul=Flatten[Table[ops[[r,1]]*hopsqb[ls,n,L,ops[[r,2]]],{n,0,kmax},{L,0,lmax*n}],3];
   hnor=Flatten[Table[Sum[hamsqb[ls,k,n,L],{k,0,n}],{n,0,kmax},{L,0,lmax*n}],3];
   evr=Simplify[Solve[hmul==hnor,unks]][[1]];
   intsrest=Flatten[Table[genintAb[ls,k],{k,kmax+1,ormax}],1];
   evr=Join[evr,Table[vb[ls,intsrest[[i]]]->0,{i,1,Length[intsrest]}]];
   ev=Table[ev[[i,1]]->(ev[[i,1]]/.ev)+(ev[[i,1]]/.evr),{i,1,Length[ev]}],
   {r,1,Length[ors]}];
ev];

(** Conversion of interaction to spectroscopic notation **)
lab={"s","p","d","f","g","h","i","j","k","b"};
labf[l_]:=lab[[l+1]];
zeon={"0","1","2","3","4","5","6","7","8","9","10",
      "11","12","13","14","15","16","17","18","19","20"};
labL[lnvaL_]:=
Block[{l,n,v,a,L,snl},
l=lnvaL[[1]]; n=lnvaL[[2]]; v=lnvaL[[3]]; a=lnvaL[[4]]; L=lnvaL[[5]]; 
snl=Table[l,{i,1,n}];
Which[n==1,labf[l],
      mulv[l,v,L]>1,
      Apply[StringJoin,Join[Map[labf,snl],{"(",zeon[[v+1]],zeon[[a+1]],zeon[[L+1]],")"}]],
      muln[l,n,L]>1,
      Apply[StringJoin,Join[Map[labf,snl],{"(",zeon[[v+1]],zeon[[L+1]],")"}]],
      True,Apply[StringJoin,Join[Map[labf,snl],{"(",zeon[[L+1]],")"}]]]];
labnoL[lnvaL_]:=
Block[{l,n,v,a,L,snl},
l=lnvaL[[1]]; n=lnvaL[[2]]; v=lnvaL[[3]]; a=lnvaL[[4]]; L=lnvaL[[5]]; 
snl=Table[l,{i,1,n}];
Which[n==1,labf[l],
      mulv[l,v,L]>1,
      Apply[StringJoin,Join[Map[labf,snl],{"(",zeon[[v+1]],zeon[[a+1]],")"}]],
      muln[l,n,L]>1,
      Apply[StringJoin,Join[Map[labf,snl],{"(",zeon[[v+1]],")"}]],
      True,Apply[StringJoin,Map[labf,snl]]]];

(* Conversion from bra or ket to string for k>=2 *)
(* Notation: bk={{n1,v1,a1,L1,I1},{n2,v2,a2,L2,I2,...}} *)
bktos[ls_,bk_]:=
Block[{k,ks,k0,ls0,bk0,bkl0},
k=Apply[Plus,bk[[All,1]]]; ks=bk[[1,1]];
ls0=If[ls[[1]]==0,Drop[ls,1],ls];
bk0=If[ls[[1]]==0,Drop[bk,1],bk]; k0=k-ks;
bkl0=Table[Join[{ls0[[i]]},bk0[[i]]],{i,1,Length[ls0]}];
bkl0=Select[bkl0,(#[[2]]!=0)&];
Which[ks==k,StringJoin[Map[labf,Table[0,{i,1,ks}]]],
      ks==0,bkl0tos[bkl0],
      True,Apply[StringJoin,Join[Map[labf,Table[0,{i,1,ks}]],{bkl0tos[bkl0]}]]]];
(* Notation: bk0={{l1,n1,v1,a1,L1,I1},{l2,n2,v2,a2,L2,I2,...}}!={} with all ni>0 *)
bkl0tos[bkl0_]:=
Block[{d},
d=Length[bkl0];
Which[d==1,labnoL[bkl0[[1]]],
      d==2,StringJoin[{labL[bkl0[[1]]],labL[bkl0[[2]]]}],
      d==3,StringJoin[{labL[bkl0[[1]]],labL[bkl0[[2]]],labL[bkl0[[3]]]}]]];

vb[ls_,int_]:=
Block[{bra,sbra,ket,sket,kb,kk,k,Lb,Lk,L},
bra=int[[1]]; ket=int[[2]];
kb=Apply[Plus,bra[[All,1]]]; kk=Apply[Plus,ket[[All,1]]]; k=kb;
If[kb!=kk,Print["Interaction does not conserve boson number"]; Abort[]];
Lb=bra[[-1,5]]; Lk=ket[[-1,5]]; L=Lb;
If[Lb!=Lk,Print["Interaction is not scalar"]; Abort[]];
Which[k==0,E0,
      k==1,e[labf[Select[bra,(#[[1]]!=0)&][[1,-1]]]],
      k>1,sbra=bktos[ls,bra]; sket=bktos[ls,ket];
      v[StringJoin[{sbra,",",sket,";",zeon[[L+1]]}]]]];
